```{r}
library(EnvStats)
library(dplyr)
library(car)
library(klaR)
library(tidyverse)
library(leaps)
library(rgbif)
library(rgeos)
library(rgdal)
library(sp)
library(sf)
library(stringr)
library(olsrr)
#log output and code
my_log <- file("my_log.txt") # File name of output log
sink(my_log, append = TRUE, type = "output") # Writing console output to log file
sink(my_log, append = TRUE, type = "message")
cat(readChar(rstudioapi::getSourceEditorContext()$path, # Writing currently opened R script to file
             file.info(rstudioapi::getSourceEditorContext()$path)$size))
```

```{r}
#read data and get rid of unwanted columns
df <- read.csv("homes_for_model.csv")

df$numPhoto <- df$numPhoto + 4
df$parcelRes <- ifelse(df$mf == 0, df$parcel, df$livingArea)
df$numDwellings <- log(df$numDwellings)

both.lose <- c( "mfYear", "mfBath", "mfBed", "minLotApt", "maxDensity", "chars",  "month", "timeAbs", "roosevelt", "zeroPhoto", "chars", "recent", "goodElem", "landValue", "minLotOne", "res", "midElem", "pr5", "lFreq", "wordLen", "pr7", "pr10", "words", "time", "pacNSA", "usNSA")

both <- df[!colnames(df) %in% both.lose]
```


```{r}
#function to check model for adequacy
model_adequacy <- function(model) {
  print(summary(model))
  print(ols_test_normality(model))
  plot(model)
  #print PRESS
  pr <- resid(model)/(1 - lm.influence(model)$hat)
  sum(pr ^ 2)
} 
```


```{r echo=FALSE}
#Create full model
fm <- lm(price ~ ., data=both)
summary(fm)
ols_test_normality(fm)
pr <- resid(fm)/(1 - lm.influence(fm)$hat)
sum(pr ^ 2)
```

```{r}
#use the all models method for OLS
models <- regsubsets(price ~ . + mf:livingArea, data = both, intercept = TRUE, nvmax = 36, really.big = TRUE)
results <- summary(models)
best <- data.frame(
  Adj.R2 = which.max(results$adjr2),
  CP = which.min(results$cp),
  BIC = which.min(results$bic)
)

coef(models, c(best$Adj.R2, best$CP, best$BIC))
```

```{r}
#OLS model building and get PRESS statistic
m <- lm(price ~ livingArea + yearBuilt  + numDwellings + seasonal + pacSA + parcelRes + combined + mf + r10 + mf:livingArea, data = both)
summary(m)
ols_test_normality(m)
ols_test_correlation(m)
round(m$coefficients, 5)
pr <- resid(m)/(1 - lm.influence(m)$hat)
sum(pr ^ 2)
plot(m)
summary(m)
```
```{r}
m2 <- lm(price ~ livingArea  + combined + mf + r10 + mf:livingArea, data = both)
summary(m2)
pr <- resid(m2)/(1 - lm.influence(m2)$hat)
sum(pr ^ 2)
```

```{r}
#make weights
m.weights <- 1/lm(abs(m$residuals) ~ m$fitted.values)$fitted.values^2
#use the all models method with weights
models <- regsubsets(price ~ . + mf:livingArea, data = both, intercept = TRUE, nvmax = 36, really.big = TRUE, weights = m.weights)
results <- summary(models)
best <- data.frame(
  Adj.R2 = which.max(results$adjr2),
  CP = which.min(results$cp),
  BIC = which.min(results$bic)
)
coef(models, c(best$Adj.R2, best$CP, best$BIC))
```


```{r}
#WLS model
wm <- lm(price ~ livingArea + yearBuilt + numDwellings + combined  + mf + r10  + mf:livingArea, data = both, weights = m.weights)
summary(wm)
ols_test_normality(wm)
pr <- resid(wm)/(1 - lm.influence(wm)$hat)
sum(pr ^ 2)
round(wm$coefficients, 5)
```


```{r}
wm2 <- lm(price ~ livingArea + combined + mf + r10  + mf:livingArea, data = both, weights = m.weights)
summary(wm2)
```

```{r}
wm3 <- lm(price ~ livingArea + yearBuilt + numDwellings + r7 + Freq + combined  + mf + r10  + mf:livingArea + rating, data = both, weights = m.weights)
```



```{r}
plot(wm)
```

```{r}
yhat <- mean(both$price)
sum((predict(wm) - yhat)^2)
sum(wm$residuals^2)
```

```{r}
plot(wm$fitted.values , stdres(wm), main="Fitted vs R-Student for Regressor Transformation", xlab = "Fitted Values", ylab = "R-Student")
abline(0, 0, col= "red")
```

```{r}
qqnorm(stdres(wm))
qqline(stdres(wm), col= "red")
```

```{r}
data.price <- both[c("price", "livingArea", "combined", "usSA", "seasonal", "parcelRes", "r10", "a2", "mf")]
data <- both[c("livingArea", "yearBuilt", "combined", "numDwellings","r10","mf")]
```

```{r}
vif(wm)
```

```{r}
plot(both$dateSold, rstudent(wm), main="Date Sold vs R-Student", xlab="Date Sold (Days since 4/1/2018)", ylab="R-Student", ylim=c(-3,3))
abline(0, 0, col= "red")
```

```{r}
plot(wm$fitted.values, studres(wm))
```

```{r}
medians <- apply(both, 2, median)
both$mad <- medians
```

```{r}
n <- nrow(both)
p <- 9
covratio_filter <- abs(covratio(wm)) < 1 - (3*p/n)
covratio_filter2 <- abs(covratio(wm)) > 1 + (3*p/n)
wm.covr <- abs(covratio(wm))
wm.covr[covratio_filter]
wm.covr[covratio_filter2]
```

```{r}
wm.cooks <- cooks.distance(wm)
cookf <- pf(0.20, p, n-p)
wm.cooks[wm.cooks >  cookf]
```

```{r}
dfb <- abs(dfbetas(wm))
(2/sqrt(n))
round(dfb,2)
plot(wm)
```

```{r}
vif(wm, data=both)
X <- as.matrix(both[c("livingArea", "yearBuilt","combined", "numDwellings", "r10", "mf", "mfArea")])
XtX <- t(X) %*% X
eigen(XtX)$values
cond.index(wm, data=both)
```

```{r}
p <- 7
n <- nrow(both)
constm <- lm(price ~ 1, data = both)
yhat <- mean(both$price)
SSres <- sum(wm$residuals^2)
MSres <- SSres / (n - p)
SSt <- sum((both$price - yhat)^2)
SSreg <- sum((wm$fitted.values - yhat)^2)
MSreg <- SSreg / p
SSreg
SSres
SSreg + SSres
MSreg
MSres
MSreg/MSres
```

```{r}
summary(wm)
anova(wm)
```

```{r}
test <- read.csv("homes_for_model_val2.csv")
test$numDwellings <- log(test$numDwellings)


predictions1 <- predict(wm, test)
predictions2 <- predict(wm2, test)
predictions3 <- predict(wm3, test)

data.frame(R2 = R2(predictions1, test$price),
            RMSE = RMSE(predictions1, test$price),
            MAE = MAE(predictions1, test$price))

wm1.i <- RMSE(predictions1, test$price)/mean(test$price)

data.frame(R2 = R2(predictions2, test$price),
            RMSE = RMSE(predictions2, test$price),
            MAE = MAE(predictions2, test$price))

wm2.i <- RMSE(predictions2, test$price)/mean(test$price)

data.frame(R2 = R2(predictions3, test$price),
            RMSE = RMSE(predictions3, test$price),
            MAE = MAE(predictions3, test$price))

wm3.i <- RMSE(predictions3, test$price)/mean(test$price)
```

```{r}
test <- read.csv("homes_for_model_val_extrap2.csv")
test$numDwellings <- log(test$numDwellings)


predictions1 <- predict(wm, test)
predictions2 <- predict(wm2, test)
predictions3 <- predict(wm3, test)

data.frame(R2 = R2(predictions1, test$price),
            RMSE = RMSE(predictions1, test$price),
            MAE = MAE(predictions1, test$price))

wm1.e <- RMSE(predictions1, test$price)/mean(test$price)


data.frame(R2 = R2(predictions2, test$price),
            RMSE = RMSE(predictions2, test$price),
            MAE = MAE(predictions2, test$price))

wm2.e <- RMSE(predictions2, test$price)/mean(test$price)


data.frame(R2 = R2(predictions3, test$price),
            RMSE = RMSE(predictions3, test$price),
            MAE = MAE(predictions3, test$price))

wm3.e <- RMSE(predictions3, test$price)/mean(test$price)
```
```{r}
wm1.i + wm1.e
wm2.i + wm2.e
wm3.i + wm3.e
```



```{r}
closeAllConnections() 
```

